export default {
  K: 4,
  JACCARD_SIMILARITY_THRESHOLD: 0.8,
  MINHASH_SIMILARITY_THRESHOLD: 0.8,
  LSH_BAND_SIZE: 4,
  MINHASH_MAX_POSSIBLE_SHINGLES: Math.pow(2, 32) - 1,
  MINHASH_NEXT_PRIME: 4294967311,
  MINHASH_NUMBER_OF_HASHES: 128
};
